### ISSUE TITLE
Undefined references to 'boost' 1.63

### ISSUE THREAD

**Issue by sagitter** [mkeeter/antimony#178] opened 2017-02-07 11:35 UTC
Hi all.

`antimony-0.9.3b` is not compiling on Fedora _rawhide_ for `undefined reference` errors:

```
[100%] Linking CXX executable antimony
cd /builddir/build/BUILD/antimony-0.9.3b/build/app && /usr/bin/cmake -E cmake_link_script CMakeFiles/antimony.dir/link.txt --verbose=1
/usr/bin/c++   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -fPIC -pie -DNDEBUG -DRELEASE  -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fPIC -pie CMakeFiles/antimony.dir/app/main.cpp.o CMakeFiles/antimony.dir/app/app.cpp.o CMakeFiles/antimony.dir/app/update.cpp.o CMakeFiles/antimony.dir/app/colors.cpp.o CMakeFiles/antimony.dir/canvas/scene.cpp.o CMakeFiles/antimony.dir/canvas/canvas_view.cpp.o CMakeFiles/antimony.dir/canvas/info.cpp.o CMakeFiles/antimony.dir/canvas/inspector/frame.cpp.o CMakeFiles/antimony.dir/canvas/inspector/export.cpp.o CMakeFiles/antimony.dir/canvas/inspector/title.cpp.o CMakeFiles/antimony.dir/canvas/inspector/buttons.cpp.o CMakeFiles/antimony.dir/canvas/inspector/util.cpp.o CMakeFiles/antimony.dir/canvas/datum_row.cpp.o CMakeFiles/antimony.dir/canvas/datum_editor.cpp.o CMakeFiles/antimony.dir/canvas/datum_port.cpp.o CMakeFiles/antimony.dir/canvas/subdatum/subdatum_frame.cpp.o CMakeFiles/antimony.dir/canvas/subdatum/subdatum_editor.cpp.o CMakeFiles/antimony.dir/canvas/subdatum/subdatum_row.cpp.o CMakeFiles/antimony.dir/canvas/connection/base.cpp.o CMakeFiles/antimony.dir/canvas/connection/connection.cpp.o CMakeFiles/antimony.dir/canvas/connection/dummy.cpp.o CMakeFiles/antimony.dir/window/base.cpp.o CMakeFiles/antimony.dir/window/canvas.cpp.o CMakeFiles/antimony.dir/window/viewport.cpp.o CMakeFiles/antimony.dir/window/quad.cpp.o CMakeFiles/antimony.dir/window/base_viewport_window.cpp.o CMakeFiles/antimony.dir/window/script_window.cpp.o CMakeFiles/antimony.dir/graph/constructor/populate.cpp.o CMakeFiles/antimony.dir/graph/proxy/graph.cpp.o CMakeFiles/antimony.dir/graph/proxy/node.cpp.o CMakeFiles/antimony.dir/graph/proxy/script.cpp.o CMakeFiles/antimony.dir/graph/proxy/datum.cpp.o CMakeFiles/antimony.dir/graph/proxy/subdatum.cpp.o CMakeFiles/antimony.dir/graph/proxy/base_datum.cpp.o CMakeFiles/antimony.dir/graph/hooks/hooks.cpp.o CMakeFiles/antimony.dir/graph/hooks/export.cpp.o CMakeFiles/antimony.dir/graph/hooks/ui.cpp.o CMakeFiles/antimony.dir/graph/hooks/title.cpp.o CMakeFiles/antimony.dir/graph/serialize/serializer.cpp.o CMakeFiles/antimony.dir/graph/serialize/deserializer.cpp.o CMakeFiles/antimony.dir/script/syntax.cpp.o CMakeFiles/antimony.dir/script/editor.cpp.o CMakeFiles/antimony.dir/script/frame.cpp.o CMakeFiles/antimony.dir/undo/undo_command.cpp.o CMakeFiles/antimony.dir/undo/undo_add_node.cpp.o CMakeFiles/antimony.dir/undo/undo_add_datum.cpp.o CMakeFiles/antimony.dir/undo/undo_delete_datum.cpp.o CMakeFiles/antimony.dir/undo/undo_delete_multi.cpp.o CMakeFiles/antimony.dir/undo/undo_delete_node.cpp.o CMakeFiles/antimony.dir/undo/undo_delete_link.cpp.o CMakeFiles/antimony.dir/undo/undo_move_node.cpp.o CMakeFiles/antimony.dir/undo/undo_move_datum.cpp.o CMakeFiles/antimony.dir/undo/undo_change_script.cpp.o CMakeFiles/antimony.dir/undo/undo_change_expr.cpp.o CMakeFiles/antimony.dir/undo/undo_stack.cpp.o CMakeFiles/antimony.dir/dialog/exporting.cpp.o CMakeFiles/antimony.dir/dialog/resolution.cpp.o CMakeFiles/antimony.dir/export/export_mesh.cpp.o CMakeFiles/antimony.dir/export/export_heightmap.cpp.o CMakeFiles/antimony.dir/export/export_worker.cpp.o CMakeFiles/antimony.dir/viewport/scene.cpp.o CMakeFiles/antimony.dir/viewport/gl.cpp.o CMakeFiles/antimony.dir/viewport/view.cpp.o CMakeFiles/antimony.dir/viewport/image.cpp.o CMakeFiles/antimony.dir/viewport/control/control.cpp.o CMakeFiles/antimony.dir/viewport/control/control_instance.cpp.o CMakeFiles/antimony.dir/viewport/control/point.cpp.o CMakeFiles/antimony.dir/viewport/control/wireframe.cpp.o CMakeFiles/antimony.dir/viewport/render/instance.cpp.o CMakeFiles/antimony.dir/viewport/render/task.cpp.o CMakeFiles/antimony.dir/antimony_automoc.cpp.o CMakeFiles/antimony.dir/antimony_automoc.dir/qrc_gl_2HPAS2ZRQXYTL6.cpp.o  -o antimony -rdynamic /usr/lib64/libQt5OpenGL.so.5.7.1 /usr/lib64/libQt5Network.so.5.7.1 /usr/lib64/libQt5Concurrent.so.5.7.1 ../lib/graph/libSbGraph.a ../lib/fab/libSbFab.a /usr/lib64/libQt5Widgets.so.5.7.1 /usr/lib64/libQt5Gui.so.5.7.1 /usr/lib64/libQt5Core.so.5.7.1 -lpython3.6m -lboost_python3 -lpng -lz 
../lib/graph/libSbGraph.a(proxy.cpp.o): In function `PyInit__proxy':
/builddir/build/BUILD/antimony-0.9.3b/lib/graph/src/proxy.cpp:103: undefined reference to `boost::python::detail::init_module(PyModuleDef&, void (*)())'
../lib/graph/libSbGraph.a(hooks.cpp.o): In function `PyInit__scriptIO':
/builddir/build/BUILD/antimony-0.9.3b/lib/graph/src/hooks/hooks.cpp:23: undefined reference to `boost::python::detail::init_module(PyModuleDef&, void (*)())'
CMakeFiles/antimony.dir/graph/hooks/hooks.cpp.o: In function `PyInit__AppHooks':
/builddir/build/BUILD/antimony-0.9.3b/app/graph/hooks/hooks.cpp:20: undefined reference to `boost::python::detail::init_module(PyModuleDef&, void (*)())'
../lib/fab/libSbFab.a(fab.cpp.o): In function `PyInit__fabtypes':
/builddir/build/BUILD/antimony-0.9.3b/lib/fab/src/fab.cpp:22: undefined reference to `boost::python::detail::init_module(PyModuleDef&, void (*)())'
collect2: error: ld returned 1 exit status
```
Full log: https://kojipkgs.fedoraproject.org//work/tasks/7313/17647313/build.log

Boost-1.63
GCC-7.0.1

**Comment by mkeeter** [comment] 2017-02-07 13:21
This kind of error is caused because `boost::python` method signatures change between Python 2 and Python 3 bindings (Antimony is using the latter).  [Here's](http://stackoverflow.com/questions/5810101/undefined-boost-python-symbol-boostpythondetailinit-module) someone seeing a similar issue.

This is a bit confusing, though, because the linker flags include `-lboost_python3`.

The SO link above suggests installing `python-dev`; I'd also try dumping the symbols from `boost_python3` and making sure that there exists one with the right signature.

**Comment by sagitter** [comment] 2017-02-08 14:12
Could be related to this `CMake` warning?

```
-- Detecting CXX compile features - done
-- Found PythonLibs: /usr/lib64/libpython3.6m.so (found suitable version "3.6.0", minimum required is "3.3") 
CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:1518 (message):
  No header defined for python3; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:17 (find_package)
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
```

**Comment by sagitter** [comment] 2017-02-09 09:32
Looks like a bug of Boost on Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1420086#c8

**Comment by mkeeter** [comment] 2017-02-09 13:25
Hah, there's a similar issue in the MINGW packaging– I filed a bug for it [here](https://github.com/Alexpux/MINGW-packages/issues/2028).  I guess no one is actually using `boost::python3`, so these things are left unnoticed...

**Comment by jwakely** [comment] 2017-02-16 19:57
Caused by https://github.com/boostorg/build/issues/163

The Fedora boost package is rebuilding now with a workaround.

**Comment by jhasse** [comment] 2017-07-20 12:17
This should now be fixed, right?

**Comment by jwakely** [comment] 2017-07-20 12:26
Yes. If anybody is still getting this error on Fedora they need to update their system to the latest boost packages.

**Comment by mkeeter** [comment] 2017-07-20 14:07
Thanks for following up – I'll close since this is now fixed upstream.

**Closed by mkeeter** 2017-07-20 14:07 UTC

**Comment by ComFreek** [comment] 2018-07-21 08:12
I am facing the same issue with Msys2 and Mingw.

My Boost build looks as follows:

- Instead of `./bootstrap.sh` I am using directly a custom `project-config.jam`, see below.
- I call `./b2 include=/mingw64/include/python3.7m -q cxxflags="-Wno-deprecated-declarations -Wno-strict-aliasing -Wno-maybe-uninitialized -D_hypot=hypot"`.<br>
  The first parts of its output are also below, note especially the `The system cannot find the file specified` error message. Unfortunately it does not say which file path.
  That message disappears if I comment out the `using python` line in `project-config.jam`. I've tripled-checked that every path there exists within an Mingw64 shell.

With Process Monitor, I also traced failed syscalls with result `NO SUCH FILE` and some other properties on the queried path to exclude all syscalls that have definitely nothing to do with Python. See the list at the end of this comment, maybe someone can spot a file which should actually be there.

```
# Boost.Build Configuration
# Automatically generated by bootstrap.sh

import option ;
import feature ;

# Compiler configuration. This definition will be used unless
# you already have defined some toolsets in your user-config.jam
# file.
if ! gcc in [ feature.values <toolset> ]
{
    using gcc ; 
}

project : default-build <toolset>gcc ;

# List of --with-<library> and --without-<library>
# options. If left empty, all libraries will be built.
# Options specified on the command line completely
# override this variable.
libraries =  --with-python ;

# These settings are equivivalent to corresponding command-line
# options.
option.set prefix : /usr/local ;
option.set exec-prefix : /usr/local ;
option.set libdir : /usr/local/lib ;
option.set includedir : /usr/local/include ;

# Stop on first error
option.set keep-going : false ;

using python : 3.7 : /mingw64/bin/python3.7m.exe : /mingw64/include/python3.7m : /mingw64/lib/python3.7/config-3.7m ;
```

```
The system cannot find the file specified.
Performing configuration checks

    - default address-model    : 64-bit (cached)
    - default architecture     : x86 (cached)

Building the Boost C++ Libraries.


    - symlinks supported       : yes (cached)

Component configuration:

    - atomic                   : not building
[ CUT ]
```

```
"Path","Result","Detail"
"D:\Downloads\boost_1_67_0\python.jam","NO SUCH FILE","Type: QueryDirectory, Filter: python.jam"
"D:\Downloads\boost_1_67_0\stage\lib\libboost_python37-mgw73-mt-d-x32-1_67.a","NO SUCH FILE","Type: QueryDirectory, Filter: libboost_python37-mgw73-mt-d-x32-1_67.a"
"D:\Downloads\boost_1_67_0\stage\lib\libboost_python37-mgw73-mt-x32-1_67.a","NO SUCH FILE","Type: QueryDirectory, Filter: libboost_python37-mgw73-mt-x32-1_67.a"
"D:\Downloads\boost_1_67_0\stage\lib\libboost_python37-mgw73-mt-d-x64-1_67.a","NO SUCH FILE","Type: QueryDirectory, Filter: libboost_python37-mgw73-mt-d-x64-1_67.a"
"D:\Downloads\boost_1_67_0\stage\lib\libboost_python37-mgw73-mt-x64-1_67.a","NO SUCH FILE","Type: QueryDirectory, Filter: libboost_python37-mgw73-mt-x64-1_67.a"
"C:\tools\msys64\mingw64\include\python3.7m\limits.h","NO SUCH FILE","Type: QueryDirectory, Filter: limits.h"
"C:\tools\msys64\mingw64\include\python3.7m\stddef.h","NO SUCH FILE","Type: QueryDirectory, Filter: stddef.h"
"C:\tools\msys64\mingw64\include\python3.7m\stdarg.h","NO SUCH FILE","Type: QueryDirectory, Filter: stdarg.h"
"C:\tools\msys64\mingw64\include\python3.7m\stdio.h","NO SUCH FILE","Type: QueryDirectory, Filter: stdio.h"
"C:\tools\msys64\mingw64\include\python3.7m\stdlib.h","NO SUCH FILE","Type: QueryDirectory, Filter: stdlib.h"
"C:\tools\msys64\mingw64\include\python3.7m\assert.h","NO SUCH FILE","Type: QueryDirectory, Filter: assert.h"
"C:\tools\msys64\mingw64\include\python3.7m\errno.h","NO SUCH FILE","Type: QueryDirectory, Filter: errno.h"
"C:\tools\msys64\mingw64\include\python3.7m\ctype.h","NO SUCH FILE","Type: QueryDirectory, Filter: ctype.h"
"C:\tools\msys64\mingw64\include\python3.7m\wchar.h","NO SUCH FILE","Type: QueryDirectory, Filter: wchar.h"
"C:\tools\msys64\mingw64\include\python3.7m\basetsd.h","NO SUCH FILE","Type: QueryDirectory, Filter: basetsd.h"
"C:\tools\msys64\mingw64\include\python3.7m\io.h","NO SUCH FILE","Type: QueryDirectory, Filter: io.h"
"C:\tools\msys64\mingw64\include\python3.7m\float.h","NO SUCH FILE","Type: QueryDirectory, Filter: float.h"
"C:\tools\msys64\mingw64\include\python3.7m\string.h","NO SUCH FILE","Type: QueryDirectory, Filter: string.h"
"C:\tools\msys64\mingw64\include\python3.7m\math.h","NO SUCH FILE","Type: QueryDirectory, Filter: math.h"
"C:\tools\msys64\mingw64\include\python3.7m\time.h","NO SUCH FILE","Type: QueryDirectory, Filter: time.h"
"C:\tools\msys64\mingw64\include\python3.7m\unistd.h","NO SUCH FILE","Type: QueryDirectory, Filter: unistd.h"
"C:\tools\msys64\mingw64\include\python3.7m\pth.h","NO SUCH FILE","Type: QueryDirectory, Filter: pth.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\patchlevel.h","NO SUCH FILE","Type: QueryDirectory, Filter: patchlevel.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\pyconfig.h","NO SUCH FILE","Type: QueryDirectory, Filter: pyconfig.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\pyport.h","NO SUCH FILE","Type: QueryDirectory, Filter: pyport.h"
"C:\tools\msys64\mingw64\include\python3.7m\inttypes.h","NO SUCH FILE","Type: QueryDirectory, Filter: inttypes.h"
"C:\tools\msys64\mingw64\include\python3.7m\ieeefp.h","NO SUCH FILE","Type: QueryDirectory, Filter: ieeefp.h"
"C:\tools\msys64\mingw64\include\python3.7m\sys","NO SUCH FILE","Type: QueryDirectory, Filter: sys"
"C:\tools\msys64\mingw64\include\python3.7m\stat.h","NO SUCH FILE","Type: QueryDirectory, Filter: stat.h"
"C:\tools\msys64\mingw64\include\python3.7m\wctype.h","NO SUCH FILE","Type: QueryDirectory, Filter: wctype.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\pymem.h","NO SUCH FILE","Type: QueryDirectory, Filter: pymem.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\object.h","NO SUCH FILE","Type: QueryDirectory, Filter: object.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\objimpl.h","NO SUCH FILE","Type: QueryDirectory, Filter: objimpl.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\pydebug.h","NO SUCH FILE","Type: QueryDirectory, Filter: pydebug.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\unicodeobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: unicodeobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\intobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: intobject.h"
"C:\tools\msys64\mingw64\include\python3.7m\intobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: intobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\longobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: longobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\floatobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: floatobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\complexobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: complexobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\rangeobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: rangeobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\stringobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: stringobject.h"
"C:\tools\msys64\mingw64\include\python3.7m\stringobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: stringobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\bufferobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: bufferobject.h"
"C:\tools\msys64\mingw64\include\python3.7m\bufferobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: bufferobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\tupleobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: tupleobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\listobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: listobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\dictobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: dictobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\methodobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: methodobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\moduleobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: moduleobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\funcobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: funcobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\classobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: classobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\fileobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: fileobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\cobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: cobject.h"
"C:\tools\msys64\mingw64\include\python3.7m\cobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: cobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\traceback.h","NO SUCH FILE","Type: QueryDirectory, Filter: traceback.h"
"C:\tools\msys64\mingw64\include\python3.7m\pthread.h","NO SUCH FILE","Type: QueryDirectory, Filter: pthread.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\sliceobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: sliceobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\cellobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: cellobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\iterobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: iterobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\descrobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: descrobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\weakrefobject.h","NO SUCH FILE","Type: QueryDirectory, Filter: weakrefobject.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\codecs.h","NO SUCH FILE","Type: QueryDirectory, Filter: codecs.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\pyerrors.h","NO SUCH FILE","Type: QueryDirectory, Filter: pyerrors.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\pystate.h","NO SUCH FILE","Type: QueryDirectory, Filter: pystate.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\modsupport.h","NO SUCH FILE","Type: QueryDirectory, Filter: modsupport.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\pythonrun.h","NO SUCH FILE","Type: QueryDirectory, Filter: pythonrun.h"
"D:\Downloads\boost_1_67_0\pythonrun.h","NO SUCH FILE","Type: QueryDirectory, Filter: pythonrun.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\ceval.h","NO SUCH FILE","Type: QueryDirectory, Filter: ceval.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\sysmodule.h","NO SUCH FILE","Type: QueryDirectory, Filter: sysmodule.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\intrcheck.h","NO SUCH FILE","Type: QueryDirectory, Filter: intrcheck.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\import.h","NO SUCH FILE","Type: QueryDirectory, Filter: import.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\abstract.h","NO SUCH FILE","Type: QueryDirectory, Filter: abstract.h"
"D:\Downloads\boost_1_67_0\boost\python\detail\pyfpe.h","NO SUCH FILE","Type: QueryDirectory, Filter: pyfpe.h"
"D:\Downloads\boost_1_67_0\python.h","NO SUCH FILE","Type: QueryDirectory, Filter: python.h"
"C:\tools\msys64\mingw64\include\python3.7m\crypt.h","NO SUCH FILE","Type: QueryDirectory, Filter: crypt.h"
"C:\tools\msys64\mingw64\include\python3.7m\stdatomic.h","NO SUCH FILE","Type: QueryDirectory, Filter: stdatomic.h"
"C:\tools\msys64\mingw64\include\python3.7m\intrin.h","NO SUCH FILE","Type: QueryDirectory, Filter: intrin.h"
"C:\tools\msys64\mingw64\include\python3.7m\immintrin.h","NO SUCH FILE","Type: QueryDirectory, Filter: immintrin.h"
"C:\tools\msys64\mingw64\include\python3.7m\cstddef","NO SUCH FILE","Type: QueryDirectory, Filter: cstddef"
"C:\tools\msys64\mingw64\include\python3.7m\cwchar","NO SUCH FILE","Type: QueryDirectory, Filter: cwchar"
"C:\tools\msys64\mingw64\include\python3.7m\cstring","NO SUCH FILE","Type: QueryDirectory, Filter: cstring"
"C:\tools\msys64\mingw64\include\python3.7m\climits","NO SUCH FILE","Type: QueryDirectory, Filter: climits"
"C:\tools\msys64\mingw64\include\python3.7m\features.h","NO SUCH FILE","Type: QueryDirectory, Filter: features.h"
"C:\tools\msys64\mingw64\include\python3.7m\utility","NO SUCH FILE","Type: QueryDirectory, Filter: utility"
"C:\tools\msys64\mingw64\include\python3.7m\algorithm","NO SUCH FILE","Type: QueryDirectory, Filter: algorithm"
"C:\tools\msys64\mingw64\include\python3.7m\ciso646","NO SUCH FILE","Type: QueryDirectory, Filter: ciso646"
"C:\tools\msys64\mingw64\include\python3.7m\string","NO SUCH FILE","Type: QueryDirectory, Filter: string"
"C:\tools\msys64\mingw64\include\python3.7m\exception","NO SUCH FILE","Type: QueryDirectory, Filter: exception"
"C:\tools\msys64\mingw64\include\python3.7m\typeinfo","NO SUCH FILE","Type: QueryDirectory, Filter: typeinfo"
"C:\tools\msys64\mingw64\include\python3.7m\cstdlib","NO SUCH FILE","Type: QueryDirectory, Filter: cstdlib"
"C:\tools\msys64\mingw64\include\python3.7m\_mingw.h","NO SUCH FILE","Type: QueryDirectory, Filter: _mingw.h"
"C:\tools\msys64\mingw64\include\python3.7m\version.h","NO SUCH FILE","Type: QueryDirectory, Filter: version.h"
"C:\tools\msys64\mingw64\include\python3.7m\syslib.h","NO SUCH FILE","Type: QueryDirectory, Filter: syslib.h"
"C:\tools\msys64\mingw64\include\python3.7m\cstdint","NO SUCH FILE","Type: QueryDirectory, Filter: cstdint"
"C:\tools\msys64\mingw64\include\python3.7m\iolib.h","NO SUCH FILE","Type: QueryDirectory, Filter: iolib.h"
"C:\tools\msys64\mingw64\include\python3.7m\ticklib.h","NO SUCH FILE","Type: QueryDirectory, Filter: ticklib.h"
"C:\tools\msys64\mingw64\include\python3.7m\signal.h","NO SUCH FILE","Type: QueryDirectory, Filter: signal.h"
"C:\tools\msys64\mingw64\include\python3.7m\memory","NO SUCH FILE","Type: QueryDirectory, Filter: memory"
"C:\tools\msys64\mingw64\include\python3.7m\iterator","NO SUCH FILE","Type: QueryDirectory, Filter: iterator"
"C:\tools\msys64\mingw64\include\python3.7m\ostream","NO SUCH FILE","Type: QueryDirectory, Filter: ostream"
"C:\tools\msys64\mingw64\include\python3.7m\type_traits.h","NO SUCH FILE","Type: QueryDirectory, Filter: type_traits.h"
"C:\tools\msys64\mingw64\include\python3.7m\msl_utility","NO SUCH FILE","Type: QueryDirectory, Filter: msl_utility"
"C:\tools\msys64\mingw64\include\python3.7m\type_traits","NO SUCH FILE","Type: QueryDirectory, Filter: type_traits"
"C:\tools\msys64\mingw64\include\python3.7m\iostream","NO SUCH FILE","Type: QueryDirectory, Filter: iostream"
"C:\tools\msys64\mingw64\include\python3.7m\assert.h?","NO SUCH FILE","Type: QueryDirectory, Filter: assert.h?"
"C:\tools\msys64\mingw64\include\python3.7m\functional","NO SUCH FILE","Type: QueryDirectory, Filter: functional"
"C:\tools\msys64\mingw64\include\python3.7m\cxxabi.h","NO SUCH FILE","Type: QueryDirectory, Filter: cxxabi.h"
"C:\tools\msys64\mingw64\include\python3.7m\atomic","NO SUCH FILE","Type: QueryDirectory, Filter: atomic"
"C:\tools\msys64\mingw64\include\python3.7m\boost","NO SUCH FILE","Type: QueryDirectory, Filter: boost"
"C:\tools\msys64\mingw64\include\python3.7m\cassert","NO SUCH FILE","Type: QueryDirectory, Filter: cassert"
"C:\tools\msys64\mingw64\include\python3.7m\endian.h","NO SUCH FILE","Type: QueryDirectory, Filter: endian.h"
"C:\tools\msys64\mingw64\include\python3.7m\machine","NO SUCH FILE","Type: QueryDirectory, Filter: machine"
"C:\tools\msys64\mingw64\include\python3.7m\ntverp.h","NO SUCH FILE","Type: QueryDirectory, Filter: ntverp.h"
"C:\tools\msys64\mingw64\include\python3.7m\winapifamily.h","NO SUCH FILE","Type: QueryDirectory, Filter: winapifamily.h"
"C:\tools\msys64\mingw64\include\python3.7m\targetconditionals.h","NO SUCH FILE","Type: QueryDirectory, Filter: targetconditionals.h"
"C:\tools\msys64\mingw64\include\python3.7m\thread","NO SUCH FILE","Type: QueryDirectory, Filter: thread"
"C:\tools\msys64\mingw64\include\python3.7m\windows.h","NO SUCH FILE","Type: QueryDirectory, Filter: windows.h"
"C:\tools\msys64\mingw64\include\python3.7m\sched.h","NO SUCH FILE","Type: QueryDirectory, Filter: sched.h"
"C:\tools\msys64\mingw64\include\python3.7m\ia64intrin.h","NO SUCH FILE","Type: QueryDirectory, Filter: ia64intrin.h"
"C:\tools\msys64\mingw64\include\python3.7m\stdint.h","NO SUCH FILE","Type: QueryDirectory, Filter: stdint.h"
"C:\tools\msys64\mingw64\include\python3.7m\limits","NO SUCH FILE","Type: QueryDirectory, Filter: limits"
"C:\tools\msys64\mingw64\include\python3.7m\builtins.h","NO SUCH FILE","Type: QueryDirectory, Filter: builtins.h"
"C:\tools\msys64\mingw64\include\python3.7m\new","NO SUCH FILE","Type: QueryDirectory, Filter: new"
"C:\tools\msys64\mingw64\include\python3.7m\iosfwd","NO SUCH FILE","Type: QueryDirectory, Filter: iosfwd"
"C:\tools\msys64\mingw64\include\python3.7m\stdexcept","NO SUCH FILE","Type: QueryDirectory, Filter: stdexcept"
"C:\tools\msys64\mingw64\include\python3.7m\cmath","NO SUCH FILE","Type: QueryDirectory, Filter: cmath"
"C:\tools\msys64\mingw64\include\python3.7m\typeindex","NO SUCH FILE","Type: QueryDirectory, Filter: typeindex"
"C:\tools\msys64\mingw64\include\python3.7m\system_error","NO SUCH FILE","Type: QueryDirectory, Filter: system_error"
"C:\tools\msys64\mingw64\include\python3.7m\string_view","NO SUCH FILE","Type: QueryDirectory, Filter: string_view"
"C:\tools\msys64\mingw64\include\python3.7m\optional","NO SUCH FILE","Type: QueryDirectory, Filter: optional"
"C:\tools\msys64\mingw64\include\python3.7m\variant","NO SUCH FILE","Type: QueryDirectory, Filter: variant"
"C:\tools\msys64\mingw64\include\python3.7m\deque","NO SUCH FILE","Type: QueryDirectory, Filter: deque"
"C:\tools\msys64\mingw64\include\python3.7m\list","NO SUCH FILE","Type: QueryDirectory, Filter: list"
"C:\tools\msys64\mingw64\include\python3.7m\vector","NO SUCH FILE","Type: QueryDirectory, Filter: vector"
"C:\tools\msys64\mingw64\include\python3.7m\map","NO SUCH FILE","Type: QueryDirectory, Filter: map"
"C:\tools\msys64\mingw64\include\python3.7m\set","NO SUCH FILE","Type: QueryDirectory, Filter: set"
"C:\tools\msys64\mingw64\include\python3.7m\bitset","NO SUCH FILE","Type: QueryDirectory, Filter: bitset"
"C:\tools\msys64\mingw64\include\python3.7m\complex","NO SUCH FILE","Type: QueryDirectory, Filter: complex"
"C:\tools\msys64\mingw64\include\python3.7m\array","NO SUCH FILE","Type: QueryDirectory, Filter: array"
"C:\tools\msys64\mingw64\include\python3.7m\tuple","NO SUCH FILE","Type: QueryDirectory, Filter: tuple"
"C:\tools\msys64\mingw64\include\python3.7m\ostream.h","NO SUCH FILE","Type: QueryDirectory, Filter: ostream.h"
"C:\tools\msys64\mingw64\include\python3.7m\cstdio","NO SUCH FILE","Type: QueryDirectory, Filter: cstdio"
"C:\tools\msys64\mingw64\include\python3.7m\mpi.h","NO SUCH FILE","Type: QueryDirectory, Filter: mpi.h"
"C:\tools\msys64\mingw64\include\python3.7m\cstdarg","NO SUCH FILE","Type: QueryDirectory, Filter: cstdarg"
"C:\tools\msys64\mingw64\include\python3.7m\excpt.h","NO SUCH FILE","Type: QueryDirectory, Filter: excpt.h"
"C:\tools\msys64\mingw64\include\python3.7m\initializer_list","NO SUCH FILE","Type: QueryDirectory, Filter: initializer_list"
"C:\tools\msys64\mingw64\include\python3.7m\locale","NO SUCH FILE","Type: QueryDirectory, Filter: locale"
"C:\tools\msys64\mingw64\include\python3.7m\iostream.h","NO SUCH FILE","Type: QueryDirectory, Filter: iostream.h"
"C:\tools\msys64\mingw64\include\python3.7m\istream","NO SUCH FILE","Type: QueryDirectory, Filter: istream"
"C:\tools\msys64\mingw64\include\python3.7m\unordered_set","NO SUCH FILE","Type: QueryDirectory, Filter: unordered_set"
"C:\tools\msys64\mingw64\include\python3.7m\unordered_map","NO SUCH FILE","Type: QueryDirectory, Filter: unordered_map"
"C:\tools\msys64\mingw64\include\python3.7m\queue","NO SUCH FILE","Type: QueryDirectory, Filter: queue"
"D:\Downloads\boost_1_67_0\python.jam","NO SUCH FILE","Type: QueryDirectory, Filter: python.jam"
```
