### ISSUE TITLE
polylines

### ISSUE THREAD

**Issue by toomuchcookies** [mkeeter/antimony#72] opened 2015-06-06 05:27 UTC
Hi, first let me thank you for your efforts. I've given antimony a quick try as well as quick-read your thesis and think there is a nice potential here.

One thing i noticed is that polylines are not available - only regular polygons. I am guessing there is no simple functional way to describe polylines, right? Right now, i could build up a polygon by boolean operations of regular polygons, but that makes for a lot of nodes that are really intransparent for the user. 

How about the user can draw a polyline and the software triangulates it in the background and outputs the union of those triangles? I guess the polyline has to always be closed implicitly.

**Comment by astronouth7303** [comment] 2015-06-06 11:21
You have to build curves up from smaller components at this time. See #22 for being able to turn that into one node.

As to why you can't do this directly, currently, see #31.

This is a duplicate of #32.

**Closed by astronouth7303** 2015-06-06 11:21 UTC
Labels: duplicate
